phpinfo:
    path: /php
    methods: [GET,POST]
    controller: App\Controller\PhpInfoController::Info

show_user :
    path: /api/user
    methods: GET
    controller: App\Controller\api\UserController::usershow


app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }    
